// Learnly 11+ / MyRank 11+ — Dynamic Dual-Design TailwindCSS Configuration
// Integrates both Stitch Projects:
// 1. "Learnly 11+ Modern Prep" (Light Mode, Indigo)
// 2. "MyRank 11+ Learning / Luminous Scholar" (Dark Mode, Electric Lime)

tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "var(--surface-container, #f5f0e0)",
        "inverse-surface": "var(--inverse-surface, #1a2a2a)",
        "tertiary": "var(--tertiary, #1a3a3a)",
        "outline": "var(--outline, #e5e5e5)",
        "primary-fixed-dim": "var(--primary-fixed-dim, #ffb084)",
        "error-container": "var(--error-container, #ffdad6)",
        "on-secondary-container": "var(--on-secondary-container, #0a0a0a)",
        "inverse-primary": "var(--inverse-primary, #ffffff)",
        "on-primary-fixed": "var(--on-primary-fixed, #ffffff)",
        "secondary-fixed": "var(--secondary-fixed, #ffb084)",
        "surface-container-highest": "var(--surface-container-highest, #ebe6d6)",
        "on-surface": "var(--on-surface, #0a0a0a)",
        "secondary": "var(--secondary, #ff4d8b)",
        "surface-container-high": "var(--surface-container-high, #ebe6d6)",
        "surface-container-low": "var(--surface-container-low, #faf5e8)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim, #e8b94a)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant, #1a3a3a)",
        "tertiary-fixed": "var(--tertiary-fixed, #a4d4c5)",
        "on-secondary-fixed": "var(--on-secondary-fixed, #0a0a0a)",
        "surface-tint": "var(--surface-tint, #0a0a0a)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed, #ffffff)",
        "surface-variant": "var(--surface-variant, #f5f0e0)",
        "on-background": "var(--on-background, #0a0a0a)",
        "secondary-container": "var(--secondary-container, #f5f0e0)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant, #0a0a0a)",
        "error": "var(--error, #ef4444)",
        "surface-container-lowest": "var(--surface-container-lowest, #ffffff)",
        "on-secondary": "var(--on-secondary, #ffffff)",
        "on-tertiary": "var(--on-tertiary, #ffffff)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim, #1a3a3a)",
        "on-surface-variant": "var(--on-surface-variant, #3a3a3a)",
        "on-error": "var(--on-error, #ffffff)",
        "background": "var(--background, #fffaf0)",
        "on-tertiary-container": "var(--on-tertiary-container, #ffffff)",
        "surface-dim": "var(--surface-dim, #ebe6d6)",
        "inverse-on-surface": "var(--inverse-on-surface, #fffaf0)",
        "tertiary-container": "var(--tertiary-container, #1a3a3a)",
        "on-error-container": "var(--on-error-container, #93000a)",
        "on-primary-container": "var(--on-primary-container, #ffffff)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant, #0a0a0a)",
        "surface": "var(--surface, #ffffff)",
        "on-primary": "var(--on-primary, #ffffff)",
        "primary-fixed": "var(--primary-fixed, #0a0a0a)",
        "surface-bright": "var(--surface-bright, #fffaf0)",
        "primary-container": "var(--primary-container, #1a3a3a)",
        "outline-variant": "var(--outline-variant, #e5e5e5)",
        "primary": "var(--primary, #0a0a0a)",
        "surface-elevated": "var(--surface-elevated, #ffffff)",
        "surface-border": "var(--surface-border, #e5e5e5)",
        "text-muted": "var(--text-muted, #6a6a6a)",
        // Clay Saturated Brand Colors
        "brand-pink": "#ff4d8b",
        "brand-teal": "#1a3a3a",
        "brand-lavender": "#b8a4ed",
        "brand-peach": "#ffb084",
        "brand-ochre": "#e8b94a",
        "brand-mint": "#a4d4c5",
        "canvas": "#fffaf0",
        "surface-soft": "#faf5e8",
        "surface-card": "#f5f0e0",
        "surface-strong": "#ebe6d6"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-tablet": "2rem",
        "gutter": "1.25rem",
        "space-lg": "1.5rem",
        "space-xl": "2.25rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "margin": "1rem",
        "space-sm": "0.5rem",
        "margin-desktop": "3rem",
        "space-2xl": "3.5rem",
        "gutter-desktop": "1.75rem"
      },
      fontFamily: {
        "display-hero": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "label-timer": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "display-hero-mobile": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "display-hero": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "headline-sm": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "body-md": ["15px", { "lineHeight": "22px", "fontWeight": "400" }],
        "label-timer": ["20px", { "lineHeight": "24px", "letterSpacing": "0.04em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "body-sm": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-md": ["22px", { "lineHeight": "28px", "fontWeight": "700" }],
        "display-hero-mobile": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.015em", "fontWeight": "800" }],
        "body-lg": ["17px", { "lineHeight": "26px", "fontWeight": "400" }]
      }
    }
  }
};
